name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd /Swift/MreAlgos;swift build -v
    - name: Run tests
      run: cd /Swift/MreAlgos;swift test -v
